# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

mod_id=asteorbar
mod_name=AsteorBar
mod_license=All-Rights-Reserved
mod_version=1.5.3
mod_group_id=com.afoxxvi
mod_authors=AsteorFox(afoxxvi)
mod_description=
minecraft_version=26.1
minecraft_version_range=[26.1,26.2)
fabric_minecraft_version_range=>=26.1 <26.2
pack_format_number=101
pack_format_minor=1
# Forge Properties
forge_version=62.0.9
forge_version_range=[62,)
loader_version_range=[62,)
eventbus_validator_version=7.0.1
# NeoForge Properties
neo_version=26.1.0.19-beta
neo_version_range=[26.1,)
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
loader_version=0.19.3
loom_version=1.17.20
# Dependencies
fabric_version=0.155.2+26.1.2
# https://linkie.shedaniel.dev/
cloth_config_version=26.1.154+fabric
mod_menu_version=18.0.0
tough_as_nails_version_forge=0
tough_as_nails_version_fabric=0
tough_as_nails_version_neoforge=0
thirst_was_taken_version_forge=0
thirst_was_taken_version_neoforge=0
mekanism_version_forge=0
dehydration_version_fabric=0
parcool_version_forge=0
irons_spellbooks_version_forge=0
feathers_version_forge=0
appleskin_version_forge=0
appleskin_version_fabric=8254965
appleskin_version_neoforge=7854456
superiorshields_version_forge=0
vampirism_version_forge=0
vampirism_version_neoforge=0
light_shield_version_neoforge=0
botania_version_forge=0
terrafirmacraft_version_forge=0
ars_nouveau_version_forge=0
origins_version_forge=0
origins_apoli_version_fabric=0
thermoo_version_fabric=10.1.5
thermoo_version_id_fabric=BeNHdIXt

