# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

mod_id=asteorbar
mod_name=AsteorBar
mod_license=All-Rights-Reserved
mod_version=1.5.3-dev
mod_group_id=com.afoxxvi
mod_authors=AsteorFox(afoxxvi)
mod_description=
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.22)
pack_format_number=61
# Forge Properties
forge_version=54.1.0
forge_version_range=[54,)
loader_version_range=[54,)
mapping_channel=official
mapping_version=1.21.4
# NeoForge Properties
neo_version=21.4.111-beta
neo_version_range=[21.4,)
neo_loader_version_range=[1,)
# read more on this at https://github.com/neoforged/NeoGradle/blob/NG_7.0/README.md#apply-parchment-mappings
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2025.02.16
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
yarn_mappings=1.21.4+build.8
loader_version=0.16.10
# Dependencies
fabric_version=0.118.5+1.21.4
# https://linkie.shedaniel.dev/
cloth_config_version=17.0.144
mod_menu_version=13.0.2
tough_as_nails_version_forge=6173794
tough_as_nails_version_fabric=6173796
tough_as_nails_version_neoforge=6173795
thirst_was_taken_version_forge=0
thirst_was_taken_version_neoforge=0
mekanism_version_forge=0
dehydration_version_fabric=0
parcool_version_forge=0
irons_spellbooks_version_forge=0
feathers_version_forge=0
appleskin_version_forge=0
appleskin_version_fabric=5864742
appleskin_version_neoforge=5864743
superiorshields_version_forge=0
vampirism_version_forge=0
vampirism_version_neoforge=0
light_shield_version_neoforge=0
botania_version_forge=0
terrafirmacraft_version_forge=0
ars_nouveau_version_forge=0
origins_version_forge=0
origins_apoli_version_fabric=0
thermoo_version_fabric=5.2.1
