# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

mod_id=asteorbar
mod_name=AsteorBar
mod_license=All-Rights-Reserved
mod_version=1.5
mod_group_id=com.afoxxvi
mod_authors=AsteorFox(afoxxvi)
mod_description=
minecraft_version=1.21
minecraft_version_range=[1.21,1.22)
pack_format_number=34
# Forge Properties
forge_version=51.0.21
forge_version_range=[51,)
loader_version_range=[51,)
mapping_channel=official
mapping_version=1.21
# NeoForge Properties
neo_version=21.0.54-beta
neo_version_range=[21.0,)
neo_loader_version_range=[1,)
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
yarn_mappings=1.21+build.8
loader_version=0.15.11
# Dependencies
fabric_version=0.100.6+1.21
# https://linkie.shedaniel.dev/
cloth_config_version=15.0.127
mod_menu_version=11.0.1
tough_as_nails_version_forge=0
tough_as_nails_version_fabric=5490272
tough_as_nails_version_neoforge=5490271
thirst_was_taken_version_forge=0
thirst_was_taken_version_neoforge=5437801
mekanism_version_forge=0
dehydration_version_fabric=0
parcool_version_forge=0
irons_spellbooks_version_forge=0
feathers_version_forge=0
appleskin_version_forge=0
appleskin_version_fabric=5429755
appleskin_version_neoforge=5447879
superiorshields_version_forge=0
vampirism_version_forge=0
vampirism_version_neoforge=0
light_shield_version_neoforge=0
botania_version_forge=0
terrafirmacraft_version_forge=0
ars_nouveau_version_forge=0
origins_version_forge=0
origins_apoli_version_fabric=0
